name: 'Photography | F. Reppekus'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44976
title: ©F. Reppekus 1998 - 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#202020'
    - '#ffffff'
    - '#6b6b6b'
    - '#b1b1b1'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
