title: ©F. Reppekus 1998 - 2016
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7040817
  brandStrength: 0.1251342
  rhythmicContrast: 0.75
  brandColors:
    - '#000000'
    - '#202020'
    - '#ffffff'
    - '#6b6b6b'
    - '#b1b1b1'
  lightness: 0.4044038
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Photography | F. Reppekus
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3174006
layout_spectrum: 1
