name: 'Photography | F. Reppekus'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6667697508819401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8316347845830023
  lightness: 0.6435191915370524
  saturation: 0.07021144195459783
  rhythmicContrast: 0.04798750067129731
purpose: []
